# FILES
defaults: # (these specify which config FILES to use)
  ############## TRAIN ###################################
  - train/config: splade
  - train/data: distil_from_ensemblePsuedoToy
  - train/model: splade_cocondenser
  ############## INDEX ###################################
  - index: msmarco
  ############## RETRIEVE ################################
  - retrieve_evaluate: all
  ############### FLOPS ##################################
  - flops: msmarco

# Direct PARAMETER setting
config:
  loss: Hybrid
  regularizer:
    L1:
      lambda_q: 0.01
      lambda_d: 0.1
      T: 200
      targeted_rep: rep
      reg: L1
  checkpoint_dir: experiments/PsuedoHardToySpladeDebug/checkpoint
  index_dir: experiments/PsuedoHardToySpladeDebug/index
  out_dir: experiments/PsuedoHardToySpladeDebug/out
  train_batch_size: 32 
  eval_batch_size: 150
  index_retrieve_batch_size: 600
  max_length: 128
  nb_iterations: 1000
  train_monitoring_freq: 50
  matching_type: DebugSplade
  record_frequency: 50
  warmup_steps: 100
  lambda_hard: 0.0001
  lambda_psuedo: 0
  # fp16: false
data:
  TRAIN:
    toy: True
# init_dict:
#   match: cosine_sim