# FILES
defaults: # (these specify which config FILES to use)
  ############## TRAIN ###################################
  - train/config: splade_monogpu
  - train/data: distil_from_ensemblePsuedoToy20
  - train/model: splade_cocondenser
  ############## INDEX ###################################
  - index: toy
  ############## RETRIEVE ################################
  - retrieve_evaluate: toy
  ############### FLOPS ##################################
  - flops: toy

# Direct PARAMETER setting
config:
  loss: Hybrid
  regularizer:
    FLOPS:
      lambda_q: 0.05
      lambda_d: 0.04
      T: 800
      targeted_rep: rep
      reg: FLOPS
  checkpoint_dir: experiments/debug/checkpoint
  index_dir: experiments/debug/index
  out_dir: experiments/debug/out
  train_batch_size: 10
  eval_batch_size: 16
  index_retrieve_batch_size: 16
  max_length: 96
  nb_iterations: 1000
  train_monitoring_freq: 100
  matching_type: splade
  record_frequency: 100
  warmup_steps: 100
  lambda_hard: 0
  lambda_Doc: 0
  lambda_Query: 0
  lambda_psuedo: 0
  q_L0_cut: 20
  d_L0_cut: 80